### ISSUE TITLE
maplist shows no maps

### ISSUE THREAD

**Issue by Ruwetuin** [beyond-all-reason/BYAR-Chobby#10]
![2019-10-13 20_01_21-Beyond all Reason](https://user-images.githubusercontent.com/11016921/66719785-6b544a00-edf4-11e9-92c6-e76587c7ff92.png)

**Comment by azaremoth** [comment]
This is because only "featured maps" (by ZeroK) are shown. I did include a "fix" in tchobby (chobby mutator for the Cursed). Should work here also.

**Comment by Ruwetuin** [comment]
i applied your changes but it does not work here, or i am missing something.

the way i mimmicked tc's method is searchign the tc codebase for 'maps' keyword and then copy the relevant/missing parts over to our codebase
see: https://github.com/beyond-all-reason/BYAR-Chobby/commit/e52f6e8bdd8f75c7b38d87dd281edd6b1b006dba

**Comment by azaremoth** [comment]
Ahh... Latest Chobby versions did ruin my changes. I did update my tchobby mutator. It should work now. Basically you need to comment out:
"if not Configuration.onlyShowFeaturedMaps then" and the respective "end" in widgets\gui_maplist_panel.lua

In additon I did remove the settings for featured maps in widgets\gui_settings_window.lua by commenting out "children[#children + 1], offset = AddCheckboxSetting(offset, i18n("only_featured_maps"), "onlyShowFeaturedMaps", true)"

**Comment by Ruwetuin** [comment]
yes it works now, thanks!
