### ISSUE TITLE
Installer flagged as infected with Trojan

### ISSUE THREAD

**Issue by Damgam** [beyond-all-reason/BYAR-Chobby#136]
Our installer exe (not the launcher) is being flagged as infected with trojan by Windows Defender right after downloading.

https://github.com/beyond-all-reason/BYAR-Chobby/releases/tag/v1.1077.0

![unknown-218](https://user-images.githubusercontent.com/25429094/124347213-b1ae9580-dbe3-11eb-8b66-e15c73901684.png)

**Comment by Damgam** [comment]
Analyst comments:


We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

Thank you for contacting Microsoft.


Click here for more information

**Comment by Beherith** [comment]
Yaaaay damgam rocks!
