### ISSUE TITLE
Better Vote interface display

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/BYAR-Chobby#146]
![image](https://user-images.githubusercontent.com/109391/132062163-f248636c-3800-4ca1-a938-493462d48274.png)
The current vote interface doesnt convey the progress of votes very well, and often bugs out. Help welcome

**Comment by Beherith** [comment]
As good as it gets, for now

**Comment by icexuick** [comment]
I saw green and red bars for votes as well! Very nice!
