### ISSUE TITLE
Flickering

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/BYAR-Chobby#150]
https://user-images.githubusercontent.com/1434248/132951654-679ed84e-ab2e-42c1-85d7-22039af038cf.mp4

Lot of flickering happening for me when the window doesn't have focus. Have got "Fix lobby flickering" enabled but doesn't seem to help, have tried toggling all those options and none make any difference to the flickering.

Windows 10

**Comment by Beherith** [comment]
Which GPU?

**Comment by Jazcash** [comment]
> Which GPU?

2080 RTX Super

**Comment by Beherith** [comment]
I have similar issues on my win10 work lappy, ill try to see monday if I can reproduce the fix flickering
It seems odd, as if old frames are inserted when chobby is idle

**Comment by Ruwetuin** [comment]
probably fixed now, at the cost of not reducing fps when offscreen

in: https://github.com/beyond-all-reason/BYAR-Chobby/commit/b6220162bda196073d074b33604b7a4d0ecf9f1e

**Comment by Jazcash** [comment]
Seems fixed, nice one
