### ISSUE TITLE
Make clear user is still in battle

### ISSUE THREAD

**Issue by Teifion** [beyond-all-reason/BYAR-Chobby#163]
When a user is present in a battle and clicks the lobby button they are moved to the lobby screen but do not leave the battle. This has many uses and should not be removed. Unfortunately at the end of a game they may return to lobby without realising they are still present in a game.

I would like to see a more obvious indicator to the user themselves they are still present in a battle. My go to would be a gently pulsing red banner at the top of their screen; it won't get in the way if they need to do something in the lobby mid-game but it will also serve as a useful reminder they need to exit the battle if the game has ended.

**Comment by Beherith** [comment]
See what Ice thinks about lovely pulsing red banners :P

**Comment by Beherith** [comment]
@icexuick

**Comment by icexuick** [comment]
I think that could help accentuate it's there / need to be interacted with

**Comment by Born2Crawl** [comment]
Why not just replace "Lobby" button with "Leave" on game over? Who needs to go to lobby and return to the finished game?

**Comment by Teifion** [comment]
Probably an edge case but returning to look at graphs? I agree this might be a better solution, if the game has ended and the user is in the lobby they also leave the battle.

**Comment by Ruwetuin** [comment]
fixed by Born2Crawl in: https://github.com/beyond-all-reason/Beyond-All-Reason/commit/58e89c16279b29e4b10164033af65bf5f9cd925a
