### ISSUE TITLE
Suggestion: Make BAR-Launcher offline playable

### ISSUE THREAD

**Issue by Jean28518** [beyond-all-reason/BYAR-Chobby#168]
Hey guys,

I love your game!
On Linux (Flatpak Version) I only can start the game, when I am connected to the network.
Could you try to fix this that automatically the last downloaded version is available, when the launcher is offline?

Best wishes 
Jean

**Comment by Beherith** [comment]
What happens if you unclick 'check for updates'? Does it not allow you to start?

**Comment by Beherith** [comment]
Ill consider this 'fixed' in our current alpha status :D
