### ISSUE TITLE
Choose color

### ISSUE THREAD

**Issue by icexuick** [beyond-all-reason/BYAR-Chobby#17]
I think it's really a primay thing in RTS - choose you team/unit color.
I cannot find this anywhere.
Could this get implemented?

**Comment by gajop** [comment]
This is now implemented, but both BAR and Evo have a widget that overrides player colors, so for it to work the widget should be disabled.

If you would prefer to use the widget instead, please disable color choosing like I did with ZK: https://github.com/Spring-Chobby/Chobby/blob/95f35a600aca3a0b2c338932fda133086a8c86c0/LuaMenu/configs/gameConfig/zk/mainConfig.lua#L117
