### ISSUE TITLE
Nicknames overlap each other after login in another account

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/BYAR-Chobby#175]
Steps to reproduce:
1. Login in account first.
2. Login in account second.

Can be avoided unlogging from first account before logging in second.
![Снимок](https://user-images.githubusercontent.com/89547444/141683668-f82817a8-1f4e-4585-b780-b45be49e1485.JPG)

Bugged:
https://youtu.be/JsJtmO89VFw

No bugged:
https://youtu.be/lpvE5-IGdWk

**Comment by Born2Crawl** [comment]
If the two accounts are "friends", you even get a notification that the second account is "online" when you're already logged in with it.

**Comment by FIr3baL** [comment]
fixed by https://github.com/beyond-all-reason/BYAR-Chobby/pull/433
