### ISSUE TITLE
openSUSE TW AppImage does not start - GPU process isn't usable

### ISSUE THREAD

**Issue by commel** [beyond-all-reason/BYAR-Chobby#177]
I'm running BYAR 1287.0 on openSUSE Tumbleweed 20211209 (a rolling release) on a AMD Ryzen 1800X with a NVIDIA GeForce RTX 2060 SUPER (driver 470.86).

Running the AppImage results in this error message:
```
 [23676:1211/134759.318154:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)
```

The process exists with return code 133, if that helps.

**Comment by commel** [comment]
Running the AppImage with
```
./Beyond-All-Reason-1.1287.0.AppImage --disable-gpu-sandbox
```
worked and I could start the installer.

**Comment by MooseOnTheLoose** [comment]
Check if AppImageLauncher is included with your distro and if not install it from your software repos before launching Appimages.

**Comment by FIr3baL** [comment]
closed - too much time and development done. Please reopen if you find any bugs reladted to this. thx
