### ISSUE TITLE
Text replaced by white splotches

### ISSUE THREAD

**Issue by krishnaravi94** [beyond-all-reason/BYAR-Chobby#179]
The text is obscured by white boxes being placed over it. This issue occurs along with [https://github.com/beyond-all-reason/Beyond-All-Reason/issues/628](url). I've attached screenshot and infolog for reference.
![no text BAR](https://user-images.githubusercontent.com/45928059/146206061-488f648a-89c5-456b-b0bd-363a3f967f65.png)
[infolog.txt](https://github.com/beyond-all-reason/BYAR-Chobby/files/7720268/infolog.txt)

**Comment by Beherith** [comment]
Does it happen every time you start, or just randomly?

**Comment by lhog** [comment]
Usually this means your GPU ran out of memory.

**Comment by FIr3baL** [comment]
@Beherith @lhog @krishnaravi94 Can we close this one ?

**Comment by lhog** [comment]
Yes
