### ISSUE TITLE
Choose/set starting location(s) in lobby

### ISSUE THREAD

**Issue by icexuick** [beyond-all-reason/BYAR-Chobby#18]
We should be able to choose starting locations from within the lobby.
Preferably in multiple ways:

- Fixed Starting Locations as set in mapinfo.lua
- Free Starting Locations with drag/drop
- Box starting area's / preferably changeable - or otherwise through extra map-coding

**Comment by icexuick** [comment]
Relevant issues: 
#41 
#37

**Comment by icexuick** [comment]
So default it should be the (fixed) startpositions, since they should be fine.
What i think is important, is that it's also visible where players start on the map, and ideally to switch/change the positions.

Same goes for startboxes, which should be visible in the map, and ideally changeable to vertical, horizontal, c1/c2 and ideally/optionally with a percentage slider (default could be 20 or 25 f.e.)

**Comment by icexuick** [comment]
Also important is a **Faction Picker**, which is not there atm.

**Comment by gajop** [comment]
relates to https://github.com/Spring-Chobby/Chobby/issues/249

**Comment by Beherith** [comment]
All are done!
