### ISSUE TITLE
Install directory amnesia.

### ISSUE THREAD

**Issue by Damgam** [beyond-all-reason/BYAR-Chobby#181]
So the bug that causes the game to reinstall in default location if you have picked another location STILL isn't fixed.
I assume this launcher cannot be fixed so can we remove possibility to install the game in non-default directory? Please?
It's really annoying to see people having this bug over and over again.

Default directory:
C:\Users\%Username%\AppData\Local\Programs\Beyond-All-Reason

@gajop

**Comment by Damgam** [comment]
I just have thought about other possible solution that i've seen in quite a few programs.
The installer should show up the entire install procedure including choosing path.

**Comment by p2004a** [comment]
As far as I understand, this is fixed now via https://github.com/beyond-all-reason/spring-launcher/issues/19 and some older electron-updater fixes.
