### ISSUE TITLE
Username change minor issue

### ISSUE THREAD

**Issue by SamiAbedin** [beyond-all-reason/BYAR-Chobby#185]
I noticed when changing my username by mistake that the current username can be taken as a new one and changed to it again, which can be fixed by a simple base case (lets say my current username is "hello", if I try changing it again to "hello, it will go through and reply back with "You will be disconnected on success. Your new username is "hello"), it doesn't affect anything really but thought it might be worth mentioning.

**Comment by FIr3baL** [comment]
This should be fixed with a change some weeks ago. Closing here.
