### ISSUE TITLE
Do NOT override Chobby widgets

### ISSUE THREAD

**Issue by gajop** [beyond-all-reason/BYAR-Chobby#20]
Overriding Chobby widgets immediately voids warranty and makes it very easy for everything to break when you update.
Use an alternative approach:
- Provide customization in Chobby itself (that's what gameConfig is for)
- Use new widgets

This has to go: https://github.com/beyond-all-reason/BYAR-Chobby/tree/master/LuaMenu/widgets/chobby/components

**Comment by Ruwetuin** [comment]
k, i removed the chobby components from the repo

plz integrate a custom gameConfig location change for the default springsettings.lua loading
see: https://github.com/Spring-Chobby/Chobby/issues/502
