### ISSUE TITLE
IceXuick: disable contain mouse and edge move cam ?

### ISSUE THREAD

**Issue by gajop** [beyond-all-reason/BYAR-Chobby#24]

**Comment by Ruwetuin** [comment]
waiting for chobby issue to be fixed: https://github.com/Spring-Chobby/Chobby/issues/502

so it can load our default springsettings again which set our custom initial config:
https://github.com/beyond-all-reason/BYAR-Chobby/blob/master/LuaMenu/configs/gameConfig/byar/defaultSettings/springsettings.lua
