### ISSUE TITLE
Message flood protection kick player from lobby 

### ISSUE THREAD

**Issue by daufinsyd** [beyond-all-reason/BYAR-Chobby#268]
Hi :)

When my friend changes settings for a play (lots of settings) and click on "Apply" he we is kicked because of:
Kicking from battle (battle lobby message flood protection).

He is the boss, so I guess all the changes he made are sent once he clicks on apply which is triggering the flood prevention message.

**Comment by AntlerForce** [comment]
Duplicate of https://github.com/beyond-all-reason/BYAR-Chobby/issues/716
