### ISSUE TITLE
IceXuick: default teamcolorpalette should be disabled if we use lobby colors

### ISSUE THREAD

**Issue by gajop** [beyond-all-reason/BYAR-Chobby#27]

**Comment by PtaQQ** [comment]
This is formulated wrongly. Let me explain. 

IceXuick wanted to have possibility to chose teamcolors in chobby. However these colors get overwritten anyway by the ingame widget. 

We would like to have that possibility so on chobby-side this ticket boils down to just this: 

add a possibility to chose players color

These colors should be standardized with color palette we use in BAR widget. Then we can disable the widget ingame if the game gets initialized with chobby. 

Might need Floris feedback here, I will let him know about this.

**Comment by PtaQQ** [comment]
After talking with Floris, we decided to ditch it, not worth the work. Let's focus on priorities.

**Comment by gajop** [comment]
Roger that. I did fix https://github.com/Spring-Chobby/Chobby/issues/503 if you ever reconsider this again. But perfectly fine if you don't as far as I'm concerned
