### ISSUE TITLE
[Feature] Save settings presets 

### ISSUE THREAD

**Issue by daufinsyd** [beyond-all-reason/BYAR-Chobby#270]
It would be time saving if we could save settings presets so that we don't need each time to enter all the settings again.

**Comment by daufinsyd** [comment]
Yes, for example when you configure the chicken settings or when you set how much resources player get at the start of the party and so on :)

**Comment by PeanutsRevenge** [comment]
Any kind of game.  If the settings could be saved [which aren't default] to a *.xxx file locally, then [as boss] when selected in the lobby, it posts them all, one by one.  Would be tripped up, if lobby not set to a preset (as for example if undeformable map had been enabled in the lobby, but it's not defined in the saved config, but water level is, it wouldn't disable undeformable map, which would stop water level change working), but it's better than at present.
It could become even more pressing as tweakdef mods grow, requiring multiple entries.

But, if it's already gonna be a part of chobby's successor, then, I'm sure we can soldier on.

**Comment by FIr3baL** [comment]
Ok, good to know that new lobby takes this request already.
I don't know how they save it, but here is my suggestion:

Having 2 levels of presets inside chobby config:
1. classPresets for each group of presets
2. globalPresets, where each is a set of classPresets
```json
{
	"classPresets": {
		"modPresets": {
			"nameOfMy1stPreset": {
				"optionX": "valueforX",
				"optionY": "valueforY"
			},
			"nameOfMy2ndPreset": "..."
		},
		"mapPresets": {
			"mapName1": {
				"my1stPresetForMapName1": {
					"mapOptionX": "valueforX",
					"mapOptionY": "valuefoxY"
				},
				"my2ndPresetForMapName1": "..."
			},
			"mapName2": "..."
		},
		"AiPresets": {
			"BarbarianAI": {
				"MyOpBarbPreset": {
					"AiOption1": "ValueForOption1",
					"AiOption2": "..."
				},
				"TweakedBarbPreset": "..."
			}
		},
		"AutohostPresets": "..."
	},
	"globalPresets" :{
		"myDefaultConfig" : {
			"modPreset" : "nameOfMy1stPreset",
			"AIPresets" : {
				"BarbarianAI" : "MyOpBarbPreset"
			}
		}
	}
}
```
I imagine:
1. a dropdown menu inside Battle Window for choosing the global preset
2. a dropdown menu on each class of options like in modOptions window, autohost settings panel,...

Maybe that concept helps as a first step for anybody willing to code this :)

**Comment by jere0500** [comment]
Hey there, I would like to have such a feature so I started implementing it.

Currently, I have a working WIP prototype.
In the prototype I can save different modoptions in a ```modfile.json``` under different presets. 
The presets can then be loaded again. I tested it both in skirmish and in multiplayer.
The loading and storing options are currently located in Adv Options under the 'Presets' tab.

![BAR_PresetTab](https://github.com/beyond-all-reason/BYAR-Chobby/assets/123008073/2d7439ae-7d5a-483b-b5da-8ef6e652d825)

![BAR_PresetTabOpen](https://github.com/beyond-all-reason/BYAR-Chobby/assets/123008073/97d8cdc8-bfd9-4470-865f-39058a4afb39)

#### modfile.json (formatted for readability)
```
{
  "defaultPreset": {
    "unit_restrictions_notech2": "1"
  },
  "Fun Raptors": {
    "unit_restrictions_notech2": "1",
    "raptor_firstwavesboost": "1",
    "raptor_spawncountmult": "1",
    "raptor_difficulty": "hard",
    "raptor_queentimemult": "0.2"
  }
}
```
(I just clicked random stuff, the presets are probably not 'fun')

This is only an early iteration. I will look forward to support more types of options and improve the implementation and  visual design.
