### ISSUE TITLE
Medit_V7 is votable on hosts but listed as unofficial

### ISSUE THREAD

**Issue by MasterBel2** [beyond-all-reason/BYAR-Chobby#284]
As title says. Thus, you can select Medit_V7 in singleplayer, but you have to manually call a vote for it (`!map Medit_V7`) in multiplayer.

**Comment by MooseOnTheLoose** [comment]
This map is not certified because it is incomplete. Technical barriers are stopping feature placement with Springboard, as maps this size repeatedly OOM for me.

**Comment by MasterBel2** [comment]
Okay, sure, but why is it votable on hosts? Should the ability to vote it be removed for the time being?
Is it worth putting "Work In Progress" on the map and letting it be played anyway? It's a wonderful map and my vote would be that it's better having it than not having it.

Is it possible to give friends a way to play "unofficial" maps privately – not just locked to singleplayer?

**Comment by MooseOnTheLoose** [comment]
@gajop and @Beherith are aware of this issue and have partially addressed it in the form of a bigmem engine build for springboard. It works well enough to let me export the textures and save the map but still OOMs in time.

**Comment by MooseOnTheLoose** [comment]
Word has it there's a new version of medit in the works...

**Comment by p2004a** [comment]
The map is now `Mediterraneum_V1` and the issue if fixed.
