### ISSUE TITLE
chobby closes when the game ends 

### ISSUE THREAD

**Issue by PtaQQ** [beyond-all-reason/BYAR-Chobby#29]
Seems to happen from time to time, after finishing game chobby is not on anymore, it returns to desktop. 

Pasting infolog from a game after which it happended: 
[infolog.txt](https://github.com/beyond-all-reason/BYAR-Chobby/files/4208458/infolog.txt)

**Comment by Beherith** [comment]
It no longer does, right @PtaQQ ?

**Comment by PtaQQ** [comment]
Yes :)
