### ISSUE TITLE
Register & Email » make it skippable

### ISSUE THREAD

**Issue by gajop** [beyond-all-reason/BYAR-Chobby#31]
Either remove email verification from GUI and drop support completely, or implement support in the backend

**Comment by icexuick** [comment]
We'd like to de-focus on registration, since many people probably like to try/test/play it solo/skirmish mode first.
Right now you are prompted to register with E-mail, but since it's not even used in the backend, i'd say there should be a 'skip' option or "later" in the register thing.

**Comment by gajop** [comment]
I don't think we should be skipping this. Why can't we setup a proper registration email system? 
Any idea @rosscosack ?

**Comment by Beherith** [comment]
@rosscosack set up email verification, but it somehow introduced more support queries then not having it. 
I am of the opinion that the registration window should ONLY show up when the multiplayer option is clicked, and not be a nasty greet screen (im used to game launchers straight up quitting if I hit cancel on registering an account).

**Comment by gajop** [comment]
I thought it was only visible when you try to make an account?
Is something forcing it to try to connect to MP?

**Comment by gajop** [comment]
@rosscosack i heard email support was added, can we close this?

**Comment by rosscosack** [comment]
Yes it is added, sorry I missed the above tags
