### ISSUE TITLE
Dependent archive "chobby test-120-8782804" not found

### ISSUE THREAD

**Issue by abma** [beyond-all-reason/BYAR-Chobby#32]
because rapid dependencies are not supported:

i.e. http://logs.springrts.com/logfiles/248/

https://github.com/gajop/spring-launcher/issues/36

**Comment by gajop** [comment]
We're explicitly downloading those:                 "games" : ["byar:test", "chobby:test", "byar-chobby:test"],

How come prds idea of chobby:test is different than springs?

**Comment by abma** [comment]
very likely because of:
https://github.com/beyond-all-reason/BYAR-Chobby/blob/master/modinfo.lua#L11

"$VERSION" is replaced with the current version of the *current* git repository which makes no sense for a dependency.

**Comment by gajop** [comment]
Ah fck, I pushed my local dev setup by accident

**Comment by gajop** [comment]
@abma thanks for reporting and pointing out the error. this has now been fixed!
