### ISSUE TITLE
Wrong initial resolution

### ISSUE THREAD

**Issue by mkow** [beyond-all-reason/BYAR-Chobby#34]
When I start BAR Chobby it always opens in 1920x1080 resolution, instead of 1920x1200 (native resolution of my monitor). As a result, at the top and bottom of the screen a see a stripe with my desktop. Not sure if this is some misconfiguration from my side, but other games have detect correct resolution + this was a fresh install of Chobby.

Starting a game also opens Spring in the wrong resolution, but at least there I have an option in settings to correct it.

Tested on Windows 10, lobby version from today.

**Comment by FIr3baL** [comment]
Can't reproduce it. Closing here.
Feel free to open new issue, if it still exists.

**Comment by mkow** [comment]
Heh, I forgot about this issue :)
I can confirm that it was fixed somewhen in these 3 years and it works correctly now, at least for me :)
