### ISSUE TITLE
Chobby should also download 1-3 maps suitable for skirmishing. 

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/BYAR-Chobby#36]
As it doesnt, and getting maps points you to additional difficulties :(

**Comment by Beherith** [comment]
I stand corrected, it downloads living lands, and even has desert 3.1 downloaded, it just doesnt recognize it. Unfortunately desert 3.1 is the default.

**Comment by gajop** [comment]
Can you provide a list of maps that you'd like to be downloaded? 

They could be added to each of the "downloads" sections (https://github.com/beyond-all-reason/BYAR-Chobby/blob/master/dist_cfg/config.json#L10) under "maps".

See https://github.com/Spring-SpringBoard/SpringBoard-Core/blob/master/dist_cfg/config.json#L74
