### ISSUE TITLE
Who is the $boss ?

### ISSUE THREAD

**Issue by victordtrr** [beyond-all-reason/BYAR-Chobby#375]
In the default lobby, I don't think actually there is a way to know who is the current boss.
Is it possible to add a command if not already implemented or a visual in the nickname to know this information ?
Thank you in advance.

**Comment by FIr3baL** [comment]
@Teifion Do you have sth. in pipeline for broadcasting bosses ?

**Comment by Teifion** [comment]
The server reads it based on messages from SPADs. You'd be able to use both `$status` and `!status` to query it but there's currently nothing the server does to broadcast that.

**Comment by FIr3baL** [comment]
fortunatily spads plugin BarManager does the job already 
stumbled open coincidentally yesterday
best of all: it also updates on removing !boss  :smile:
```
BarManager|{"BattleStateChanged": {"locked": "locked", "autoBalance": "advanced", "teamSize": "8", "nbTeams": "2", "balanceMode": "clan;skill", "preset": "team", "boss": "Fireball"}}
BarManager|{"BattleStateChanged": {"locked": "locked", "autoBalance": "advanced", "teamSize": "8", "nbTeams": "2", "balanceMode": "clan;skill", "preset": "team", "boss": ""}}
```

**Comment by FIr3baL** [comment]
bad thing ist:
we don't receive an initial state when joining a battle, only when boss changes (or other parameters change inside BarManager)
made a PR here for sending boss info on joining a battle
https://github.com/beyond-all-reason/spads_config_bar/pull/115

**Comment by FIr3baL** [comment]
@victordtrr btw - you can ask for current boss by typing $status

**Comment by victordtrr** [comment]
thank you, i know this. but a little crown icon next to the player name in the lobby could be nice !

**Comment by FIr3baL** [comment]
ok, i spent much time now to narrow this down. Talked to a lot of devs and it looks like, we will be able to introduce this feature in the future.

**Comment by FIr3baL** [comment]
crown for boss was added with https://github.com/beyond-all-reason/BYAR-Chobby/pull/439
and barmanager was fixed to always send the needed info 👍
