### ISSUE TITLE
Allow lobbies to be open to friends.

### ISSUE THREAD

**Issue by jdunns** [beyond-all-reason/BYAR-Chobby#426]
Hello! 

My family and friends enjoy the game and so far our only gripe is needing to share the lobby passwords over discord. 

I'm willing to do the work to implement a "Open to Friends" option for lobbies so friends can join without needing a password. But before I start, I'd like to know if there's any interest or if this is even in accordance with the design plans of others. 

Thanks!

**Comment by FIr3baL** [comment]
Hallo,
in chobby, i beliebe you can already join friends battles by clicking "join battle" from the drop down menu in friend list without typing a password.

**Comment by jdunns** [comment]
Oh! I've tried this but it always requires a password. I must be doing something wrong. Does the game host have to have the game open to the public to allow this? Wouldn't an open game make it appear on server lists to the public? Sorry, I am not understanding.

**Comment by FIr3baL** [comment]
Just tested this.
You can join battles from friends without entering password. 
Just leave the password field empty and click join.
![grafik](https://github.com/beyond-all-reason/BYAR-Chobby/assets/32598847/40e4cc9e-18cf-40b2-a270-d677d60b214a)

**Comment by FIr3baL** [comment]
@jdunns i talked to @Teifion, who is managing serverside things, and it's a good idea.
You can join bar discord and contact him for this.

**Comment by jdunns** [comment]
Excellent. I'll get things setup on my environment then join the discord. Thank you!
