### ISSUE TITLE
Restart needed when new version of the game is released.

### ISSUE THREAD

**Issue by Damgam** [beyond-all-reason/BYAR-Chobby#43]
Should just download missing stuff while running?

**Comment by gajop** [comment]
Just to be clear, this is about the game, not the launcher?

**Comment by Damgam** [comment]
When you're loaded into chobby, and there is new BAR update, you have to restart the lobby completely because it won't autodownload in lobby. But launcher downloads just fine

**Comment by gajop** [comment]
@Damgam Is this a new issue? My guess is the 64bit pr-downloader that comes with the engine has some bugs - I've noticed it fails to download the engine properly.

**Comment by Damgam** [comment]
I have no idea how new it is, but it definitely worked last time i've played Evo with chobby which was... Weeks ago.

**Comment by gajop** [comment]
Can you give it a try? Remove 64bit engine, manually download the same version of 32bit and do the same procedure.

**Comment by Beherith** [comment]
Works fine now :)
