### ISSUE TITLE
Maps window goes above screen on ultrawides

### ISSUE THREAD

**Issue by icexuick** [beyond-all-reason/BYAR-Chobby#44]
Max height for map window should not exceed monitor height.

![image](https://user-images.githubusercontent.com/23189106/93927870-c5a29e00-fd19-11ea-8df4-e0e1dcfc16e8.png)

**Comment by icexuick** [comment]
On restart this seems to be fixed, but not on first run.
I installed, then changed borderless to windowed (though maximized).
Second run is good, but first run should also be good.

**Comment by Beherith** [comment]
fixed!
