### ISSUE TITLE
re-arrange the right click friendst list to prevent erroneous ignores

### ISSUE THREAD

**Issue by Jarek7** [beyond-all-reason/BYAR-Chobby#447]
![image](https://github.com/beyond-all-reason/BYAR-Chobby/assets/1486115/f498abe9-3fe2-4933-b731-52c4c4882d5a)

Move ignore all the way to below Report User option to prevent people missclicking message and ignoring their friends on accident.

**Comment by FIr3baL** [comment]
I think that's a good idea and easy to change.

**Comment by FIr3baL** [comment]
After adding "Copy Name" before, "Ignore" was already moved down a bit.

Now i switched the position of friend/unfriend with Ignore/Unignore
![grafik](https://github.com/beyond-all-reason/BYAR-Chobby/assets/32598847/baa6464b-58b1-4efe-bf75-1686087569e0)

Imho that's enough :)
