### ISSUE TITLE
Connection Issue | Instant switch back to lobby/battleroom

### ISSUE THREAD

**Issue by icexuick** [beyond-all-reason/BYAR-Chobby#45]
Connection cannot be established.
Where can i find the upload-log thing? There used to be a button inside of chobby?

**Comment by gajop** [comment]
Left menu -> Help/Links -> upload log
or
Look at your system tray for BAR icon -> toggle hide -> upload log

**Comment by icexuick** [comment]
I needed to click "links" indeed - there it was.
I expected the button to be below "links"

**Comment by icexuick** [comment]
unfortunately i get this when pressing the "upload log" in-lobby
![image](https://user-images.githubusercontent.com/23189106/93982694-d4bd3680-fd81-11ea-8621-58deca6315c5.png)

**Comment by gajop** [comment]
Log upload issue has been resolved. The original issue is probably a duplicate of https://github.com/beyond-all-reason/BYAR-Chobby/issues/1 so closing
