### ISSUE TITLE
Remember options from previously hosted game

### ISSUE THREAD

**Issue by whossname** [beyond-all-reason/BYAR-Chobby#460]
My friend group always play co-op vs the AI. This means that every time we host a new lobby we need to remember to turn off Auto-balance. It would be great if the game remembered from our previous lobby that we don't use that option.

**Comment by PeanutsRevenge** [comment]
Similar was already suggested someone else, bring able to save lobby/modoptions to a local file, that can be uploaded to set all variables.
If going so far as to remember one option, may aswell take to obvious end stage of all options.
Hopefully in the next lobby :crossed_fingers:

**Comment by FIr3baL** [comment]
also see here: https://github.com/beyond-all-reason/BYAR-Chobby/issues/270

**Comment by AntlerForce** [comment]
Closed via #727
