### ISSUE TITLE
couldnt get the game to work on manjaro(native version)

### ISSUE THREAD

**Issue by dorker6** [beyond-all-reason/BYAR-Chobby#49]
log: http://logs.springrts.com/logfiles/453/
i tried to launch the game it failed to launch then tried to check for updates which also failed, launch the appimage from my Downloads folder tried launching it from terminal and GUI(nautilus). system info (havent tried win version through wine but i will) system info:
Manjaro: 20.2 Nibia (testing branch)
kernel: 5.7.19-2-MANJARO
GPU: Radeon HD 8830M / R7 250 / R7 M465X
GPU driver:amdgpu (in manjaro settings video-linux)
CPU:Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
DE: i3-wm

**Comment by gajop** [comment]
It says you don't have enough disk space.

**Comment by dorker6** [comment]
well im stupid sorry for this
