### ISSUE TITLE
(Auto) Download BarbarIAn AI into (latest) engine folder

### ISSUE THREAD

**Issue by icexuick** [beyond-all-reason/BYAR-Chobby#50]
Best way to get the BarbarIAn AI is to get the latest version from somewhere and (auto) extract it into the latest engine.
We could include it in the engine, but that is a lot slower. Barbarians gets lots of updates, almost daily... and the engine doesn't :).

So somehow it would be nice that on first install/launch of Chobby, it would check & auto download the latest version.
And perhaps in the lobby a button as well to update/check for new version of this AI as well.

(afaik we can't add in in the BAR-game, since it's a native AI)

**Comment by gajop** [comment]
Having it be downloaded & extracted is quite easy.
Checking for an updated is harder right now (the easiest solution would require it to be manually updated with a different link).

Can't we just use a stable version of Barb AI for now?

**Comment by Beherith** [comment]
It can be downloaded from: https://github.com/beyond-all-reason/BARbarIAn
Which can theoretically be hotlinked from (tested by wget-ing from 
https://github.com/beyond-all-reason/BARbarIAn/archive/master.zip
There are a few caveats: The master.zip contains everything in a single folder called BARbarIAn-master. The contents of this folder (e.g. the directory named 0.57) needs to be put into 

Beyond-All-Reason\data\AI\Skirmish\BARbarIAn\0.57
This folder does not exist by default. 

The difficulty here being a directory in the archive that needs to be renamed.

Solution A: 
[BARbarIAn_0.57.zip](https://github.com/beyond-all-reason/BYAR-Chobby/files/5417727/BARbarIAn_0.57.zip)
Take this archive, slap onto the static host, and straight up unzip its contents into Beyond-All-Reason\data\AI\Skirmish\BARbarIAn
If/when barbarian is updated, we upload a new zip, and change the respective path in chobby config.json

Solution B:
Somehow implement folder renaming on extract (super bad)

Solution C:
Git clone from barbarian repo. 

Note: this is how it should look like:
![image](https://user-images.githubusercontent.com/109391/96757029-2edb0700-13d5-11eb-84d7-ce179642466c.png)

**Comment by rlcevg** [comment]
If
> Having it be downloaded & extracted is quite easy.

then i vote for "Solution A". ZK is using similar approach: there chobby has config param with unique version_number (unique url will play same role). After chobby updated if version_number is different from saved number on client's side then it downloads new version and updates client-side number.
(is chobby going to update regularly?)

A separate thing to consider for me is version names to avoid flooding PCs with folders of dead versions. Is it good practice to delete files (specifically AI) from client's PC on update?
I'd expect new versions just being extracted over previous one, so version name will be frozen for a long time, could name it just "stable" for deployment instead of 0.57

**Comment by gajop** [comment]
Solution C

I didn't realize it was also *released* via Git. 
I think we should consider in implementing a "git downloader" system for spring-launcher. This has been on my list for quite a while now - it's useful for developers too.

On "deleting old versions" - I don't have a good solution for this yet. Old engines might also keep taking space..

**Comment by Beherith** [comment]
this is fixed, closing

**Comment by gajop** [comment]
How did you solve it?

**Comment by Beherith** [comment]
Oh, I didnt solve it, I thought it was already solved :(

**Comment by Beherith** [comment]
Engine includes Barb, thats how :)
