### ISSUE TITLE
`Skia shader compilation error`

### ISSUE THREAD

**Issue by pwaller** [beyond-all-reason/BYAR-Chobby#534]
After upgrading my Linux (NixOS) AMDGPU system to the latest version, chobby fails to load, dumping many instances of:

```
[(...):ERROR:shared_context_state.cc(81)] Skia shader compilation error
<shader source code>
Errors:
link failed but did not provide an info log
```

The GUI window opens but is blank. Downgrading my system fixes the issue.

Searching around finds various projects hitting this, notably chromium, where there is recent activity: https://bugs.chromium.org/p/chromium/issues/detail?id=1442633

# Workaround

I was able to fix this by moving `./.config/Beyond-All-Reason/GPUCache` out of the way (or deleting it). It appears a cause of the issue is that the cache key used for the shader cache is incorrect, so clearing the cache fixes things, but there may be other underlying issues.

**Comment by p2004a** [comment]
Known issue, that we can't do much about as it's bug in Chromium/Electron.
