### ISSUE TITLE
chobby users get kicked all the time due lobby status flood protection

### ISSUE THREAD

**Issue by Ruwetuin** [beyond-all-reason/BYAR-Chobby#54]
* [teh]host * Kicking Teifion from battle (battle lobby status flood protection)

**Comment by Ruwetuin** [comment]
and can lead to this:
* [teh]host * Battle ban added for user ApulSS (duration: 5 minute(s), reason: battle lobby flood protection)

**Comment by gajop** [comment]
Can you upload the log with debug server messages turned on? (Make sure you password isn't included)

**Comment by Damgam** [comment]
I'm pretty sure what happens is Chobby rapidly changing Team and/or PlayerID multiple times too fast.

**Comment by gajop** [comment]
That's my guess too but I want a log. Kinda difficult to reproduce otherwise

**Comment by Beherith** [comment]
I mitigated this spads side with:
statusFloodAutoKick:8;8 -> statusFloodAutoKick:24;8
http://planetspads.free.fr/spads/doc/spadsDoc_Settings.html#global:statusFloodAutoKick
