### ISSUE TITLE
Why does nullai have an ai options selector, whereas it does nothing

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/BYAR-Chobby#57]
Nullai should be hidden, or at the very least moved to the end. 
All AI's need a single line description of what they do.
Needs a config option for resource bonus
Needs the ability to set faction of ai

**Comment by MooseOnTheLoose** [comment]
This is still an issue, I see the confusion "why isn't my AI opponent moving?" everyday. Why offer up these barely functioning AIs?
