### ISSUE TITLE
Error downloading assets

### ISSUE THREAD

**Issue by epassaro** [beyond-all-reason/BYAR-Chobby#59]
```
[Wed Oct 28 2020 15:34:55 GMT-0300 (Argentina Standard Time) info] Begin log

[Wed Oct 28 2020 15:34:55 GMT-0300 (Argentina Standard Time) info] Log file: /home/epassaro/Documents/Beyond All Reason/spring-launcher.log

[Wed Oct 28 2020 15:34:55 GMT-0300 (Argentina Standard Time) info] Beyond-All-Reason - 1.167.0

[Wed Oct 28 2020 15:34:55 GMT-0300 (Argentina Standard Time) info] App path: /tmp/.mount_BeyondGw8iMW/resources/app.asar

[Wed Oct 28 2020 15:34:55 GMT-0300 (Argentina Standard Time) info] pr-downloader path: /tmp/.mount_BeyondGw8iMW/bin/pr-downloader

[Wed Oct 28 2020 15:34:55 GMT-0300 (Argentina Standard Time) info] Write path: /home/epassaro/Documents/Beyond All Reason

[Wed Oct 28 2020 15:34:55 GMT-0300 (Argentina Standard Time) info] Launcher configs:
[
    {
        "package": {
            "platform": "linux",
            "portable": false,
            "id": "manual-linux",
            "display": "Alpha (Direct Download)"
        },
        "display": {
            "title": "Spring Launcher"
        },
        "isolation": true,
        "auto_download": false,
        "auto_start": false,
        "no_downloads": false,
        "no_start_script": true,
        "load_dev_exts": false,
        "downloads": {
            "games": [
                "byar:test",
                "chobby:test",
                "byar-chobby:test"
            ],
            "maps": [],
            "engines": [],
            "resources": [
                {
                    "url": "https://springrts.com/dl/buildbot/default/maintenance/104.0.1-1553-gd3c0012/linux64/spring_%7bmaintenance%7d104.0.1-1553-gd3c0012_minimal-portable-linux64-static.7z",
                    "destination": "engine/104.0.1-1553-gd3c0012 maintenance",
                    "extract": true
                },
                {
                    "url": "https://spring-launcher.ams3.digitaloceanspaces.com/maps/altored_divide_bar_remake_1.55.sd7",
                    "destination": "maps/altored_divide_bar_remake_1.55.sd7",
                    "extract": false
                },
                {
                    "url": "https://spring-launcher.ams3.digitaloceanspaces.com/maps/boulder_beach_v1.sd7",
                    "destination": "maps/boulder_beach_v1.sd7",
                    "extract": false
                },
                {
                    "url": "https://spring-launcher.ams3.digitaloceanspaces.com/maps/dsdr_3.98.sd7",
                    "destination": "maps/dsdr_3.98.sd7",
                    "extract": false
                },
                {
                    "url": "https://spring-launcher.ams3.digitaloceanspaces.com/maps/quicksilver_remake_1.24.sd7",
                    "destination": "maps/quicksilver_remake_1.24.sd7",
                    "extract": false
                },
                {
                    "url": "https://spring-launcher.ams3.digitaloceanspaces.com/maps/red_comet_remake_1.8.sd7",
                    "destination": "maps/red_comet_remake_1.8.sd7",
                    "extract": false
                },
                {
                    "url": "https://spring-launcher.ams3.digitaloceanspaces.com/maps/trefoil_remake_2.20.sd7",
                    "destination": "maps/trefoil_remake_2.20.sd7",
                    "extract": false
                }
            ]
        },
        "launch": {
            "start_args": [
                "--menu",
                "rapid://byar-chobby:test"
            ],
            "engine": "104.0.1-1553-gd3c0012 maintenance"
        },
        "title": "Beyond All Reason"
    },
    {
        "package": {
            "platform": "all",
            "portable": false,
            "id": "alpha",
            "display": "Alpha"
        },
        "display": {
            "title": "Spring Launcher"
        },
        "isolation": true,
        "auto_download": false,
        "auto_start": false,
        "no_downloads": false,
        "no_start_script": true,
        "load_dev_exts": false,
        "downloads": {
            "games": [
                "byar:test",
                "chobby:test",
                "byar-chobby:test"
            ],
            "maps": [],
            "engines": [
                "104.0.1-1553-gd3c0012 maintenance"
            ],
            "resources": []
        },
        "launch": {
            "start_args": [
                "--menu",
                "rapid://byar-chobby:test"
            ]
        },
        "title": "Beyond All Reason"
    },
    {
        "package": {
            "platform": "all",
            "portable": false,
            "id": "dev-lobby",
            "display": "Dev Lobby"
        },
        "display": {
            "title": "Spring Launcher"
        },
        "isolation": true,
        "auto_download": false,
        "auto_start": false,
        "no_downloads": true,
        "no_start_script": true,
        "load_dev_exts": false,
        "downloads": {
            "games": [],
            "maps": [],
            "engines": [
                "104.0.1-1553-gd3c0012 maintenance"
            ],
            "resources": []
        },
        "launch": {
            "start_args": [
                "--menu",
                "BYAR Chobby $VERSION"
            ]
        },
        "title": "Beyond All Reason"
    }
]

[Wed Oct 28 2020 15:34:55 GMT-0300 (Argentina Standard Time) info] Default config:
{
    "package": {
        "platform": "linux",
        "portable": false,
        "id": "manual-linux",
        "display": "Alpha (Direct Download)"
    },
    "display": {
        "title": "Spring Launcher"
    },
    "isolation": true,
    "auto_download": false,
    "auto_start": false,
    "no_downloads": false,
    "no_start_script": true,
    "load_dev_exts": false,
    "downloads": {
        "games": [
            "byar:test",
            "chobby:test",
            "byar-chobby:test"
        ],
        "maps": [],
        "engines": [],
        "resources": [
            {
                "url": "https://springrts.com/dl/buildbot/default/maintenance/104.0.1-1553-gd3c0012/linux64/spring_%7bmaintenance%7d104.0.1-1553-gd3c0012_minimal-portable-linux64-static.7z",
                "destination": "engine/104.0.1-1553-gd3c0012 maintenance",
                "extract": true
            },
            {
                "url": "https://spring-launcher.ams3.digitaloceanspaces.com/maps/altored_divide_bar_remake_1.55.sd7",
                "destination": "maps/altored_divide_bar_remake_1.55.sd7",
                "extract": false
            },
            {
                "url": "https://spring-launcher.ams3.digitaloceanspaces.com/maps/boulder_beach_v1.sd7",
                "destination": "maps/boulder_beach_v1.sd7",
                "extract": false
            },
            {
                "url": "https://spring-launcher.ams3.digitaloceanspaces.com/maps/dsdr_3.98.sd7",
                "destination": "maps/dsdr_3.98.sd7",
                "extract": false
            },
            {
                "url": "https://spring-launcher.ams3.digitaloceanspaces.com/maps/quicksilver_remake_1.24.sd7",
                "destination": "maps/quicksilver_remake_1.24.sd7",
                "extract": false
            },
            {
                "url": "https://spring-launcher.ams3.digitaloceanspaces.com/maps/red_comet_remake_1.8.sd7",
                "destination": "maps/red_comet_remake_1.8.sd7",
                "extract": false
            },
            {
                "url": "https://spring-launcher.ams3.digitaloceanspaces.com/maps/trefoil_remake_2.20.sd7",
                "destination": "maps/trefoil_remake_2.20.sd7",
                "extract": false
            }
        ]
    },
    "launch": {
        "start_args": [
            "--menu",
            "rapid://byar-chobby:test"
        ],
        "engine": "104.0.1-1553-gd3c0012 maintenance"
    },
    "title": "Beyond All Reason"
}

[Wed Oct 28 2020 15:34:55 GMT-0300 (Argentina Standard Time) info] Patch to 7zip: /tmp/.mount_BeyondGw8iMW/resources/app.asar.unpacked/node_modules/7zip-bin/linux/x64/7za

[Wed Oct 28 2020 15:34:55 GMT-0300 (Argentina Standard Time) info] test

[Wed Oct 28 2020 15:34:55 GMT-0300 (Argentina Standard Time) info] bridge: listening on port: 127.0.0.1:46817

[Wed Oct 28 2020 15:34:55 GMT-0300 (Argentina Standard Time) info] Including extension: ./exts/dev_extension_loader.js...

[Wed Oct 28 2020 15:34:55 GMT-0300 (Argentina Standard Time) info] Including extension: ./exts/open_file.js...

[Wed Oct 28 2020 15:34:55 GMT-0300 (Argentina Standard Time) info] Including extension: ./exts/track_files.js...

[Wed Oct 28 2020 15:34:55 GMT-0300 (Argentina Standard Time) info] Including extension: ./exts/upload_log.js...

[Wed Oct 28 2020 15:35:11 GMT-0300 (Argentina Standard Time) info] User wants to upload?  No

[Wed Oct 28 2020 15:35:19 GMT-0300 (Argentina Standard Time) info] Step: {
    "name": "launcher_update"
}

[Wed Oct 28 2020 15:35:19 GMT-0300 (Argentina Standard Time) info] Checking for launcher update

[Wed Oct 28 2020 15:35:19 GMT-0300 (Argentina Standard Time) info] Checking for update

[Wed Oct 28 2020 15:35:19 GMT-0300 (Argentina Standard Time) info] Generated new staging user ID: 3e23dd6e-d1a8-5a9b-b208-ce998fcb17b7

[Wed Oct 28 2020 15:35:20 GMT-0300 (Argentina Standard Time) info] Update for version 1.167.0 is not available (latest version: 1.167.0, downgrade is disallowed).

[Wed Oct 28 2020 15:35:20 GMT-0300 (Argentina Standard Time) info] No update available.

[Wed Oct 28 2020 15:35:20 GMT-0300 (Argentina Standard Time) info] Step: {
    "name": "game",
    "item": "byar:test"
}

[Wed Oct 28 2020 15:35:20 GMT-0300 (Argentina Standard Time) info] Download started: byar:test, game, --filesystem-writepath,/home/epassaro/Documents/Beyond All Reason,--download-game,byar:test

[Wed Oct 28 2020 15:35:20 GMT-0300 (Argentina Standard Time) info] pr-downloader 0.7-544-gd3e5a4a

[Wed Oct 28 2020 15:35:27 GMT-0300 (Argentina Standard Time) info] [Info] ../../tools/pr-downloader/src/FileSystem/FileSystem.cpp:194:setWritePath():Using filesystem-writepath: /home/epassaro/Documents/Beyond All Reason
[Info] ../../tools/pr-downloader/src/pr-downloader.cpp:173:DownloadSetConfig():Free disk space: 392072 MB
[Info] ../../tools/pr-downloader/src/Downloader/CurlWrapper.cpp:60:DumpVersion():libcurl 7.65.3 OpenSSL/1.1.1c
[Info] ../../tools/pr-downloader/src/Downloader/CurlWrapper.cpp:42:GetTLSBackend():SSL backend #0: 'openssl' (ID: 1)
[Info] ../../tools/pr-downloader/src/Downloader/CurlWrapper.cpp:105:ValidateCaFile():Downloading https://springrts.com/dl/cacert.pem
[Progress]  74% [======================        ] 163840/221418 

[Wed Oct 28 2020 15:35:27 GMT-0300 (Argentina Standard Time) info] [Progress] 100% [==============================] 221418/221418 

[Wed Oct 28 2020 15:35:29 GMT-0300 (Argentina Standard Time) info] 

[Wed Oct 28 2020 15:35:29 GMT-0300 (Argentina Standard Time) info] [Progress]   0% [                              ] 0/0 

[Wed Oct 28 2020 15:35:30 GMT-0300 (Argentina Standard Time) warn] [Error] ../../tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:487:processMessages():CURL error(1:77): Problem with the SSL CA cert (path? access rights?) 0 (https://repos.springrts.com/repos.gz)

[Wed Oct 28 2020 15:35:32 GMT-0300 (Argentina Standard Time) info] 

[Wed Oct 28 2020 15:35:32 GMT-0300 (Argentina Standard Time) warn] [Error] ../../tools/pr-downloader/src/Downloader/Rapid/RapidDownloader.cpp:203:ParseFD():Broken /home/epassaro/Documents/Beyond All Reason/rapid/repos.springrts.com/repos.gz: 0

[Wed Oct 28 2020 15:35:33 GMT-0300 (Argentina Standard Time) warn] [Error] ../../tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:87:DownloadUrl():Error in curl Problem with the SSL CA cert (path? access rights?) (error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs)
[Error] ../../tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:207:search():Error downloading https://api.springfiles.com/json.php?category=game&torrent=true&springname=byar:test 
[Error] ../../tools/pr-downloader/src/main.cpp:195:main():No game found for byar:test
[Error] ../../tools/pr-downloader/src/main.cpp:240:main():Error occurred while downloading: 1

[Wed Oct 28 2020 15:35:33 GMT-0300 (Argentina Standard Time) error] [Error] ../../tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:87:DownloadUrl():Error in curl Problem with the SSL CA cert (path? access rights?) (error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs)
[Error] ../../tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:207:search():Error downloading https://api.springfiles.com/json.php?category=game&torrent=true&springname=byar:test 
[Error] ../../tools/pr-downloader/src/main.cpp:195:main():No game found for byar:test
[Error] ../../tools/pr-downloader/src/main.cpp:240:main():Error occurred while downloading: 1
```

**Comment by abma** [comment]
please try again, a certificate was expired:

https://springrts.com/phpbb/viewtopic.php?f=71&p=595683#p595683

**Comment by epassaro** [comment]
Same error, still not working for me.

**Comment by abma** [comment]
try to delete  /home/epassaro/Documents/Beyond All Reason/rapid/

**Comment by xyz32** [comment]
I have the same issue using the latest installer on fedora 34 KDE.
`[2021-11-19 09:00:36.177] [info]  Begin log
[2021-11-19 09:00:36.184] [info]  Log file: /media/hdd/games/Beyond All Reason/spring-launcher.log
[2021-11-19 09:00:36.185] [info]  Beyond-All-Reason - 1.1252.0
[2021-11-19 09:00:36.185] [info]  App path: /tmp/.mount_BeyondZZsdFx/resources/app.asar
[2021-11-19 09:00:36.185] [info]  pr-downloader path: /tmp/.mount_BeyondZZsdFx/bin/pr-downloader
[2021-11-19 09:00:36.185] [info]  Write path: /media/hdd/games/Beyond All Reason
[2021-11-19 09:00:36.186] [info]  Launcher configs:
[
    {
        "package": {
            "platform": "linux",
            "portable": false,
            "id": "manual-linux",
            "display": "Alpha"
        },
        "display": {
            "title": "Spring Launcher"
        },
        "isolation": true,
        "auto_download": false,
        "auto_start": false,
        "no_downloads": false,
        "no_start_script": true,
        "load_dev_exts": false,
        "route_prd_to_nextgen": false,
        "github_log_repo": null,
        "downloads": {
            "games": [
                "byar:test",
                "chobby:test",
                "byar-chobby:test"
            ],
            "maps": [],
            "engines": [],
            "resources": [
                {
                    "url": "https://github.com/beyond-all-reason/spring/releases/download/spring_bar_%7BBAR105%7D105.1.1-582-gddec320/spring_bar_.BAR105.105.1.1-582-gddec320_linux-64-minimal-portable.7z",
                    "destination": "engine/105.1.1-582-gddec320 bar",
                    "extract": true
                },
                {
                    "url": "https://github.com/beyond-all-reason/Maps/releases/download/1.0/altored_divide_bar_remake_1.55.sd7",
                    "destination": "maps/altored_divide_bar_remake_1.55.sd7",
                    "extract": false
                },
                {
                    "url": "https://github.com/beyond-all-reason/Maps/releases/download/1.0/boulder_beach_v1.sd7",
                    "destination": "maps/boulder_beach_v1.sd7",
                    "extract": false
                },
                {
                    "url": "https://github.com/beyond-all-reason/Maps/releases/download/1.0/dsdr_4.0.sd7",
                    "destination": "maps/dsdr_4.0.sd7",
                    "extract": false
                },
                {
                    "url": "https://github.com/beyond-all-reason/Maps/releases/download/1.0/quicksilver_remake_1.24.sd7",
                    "destination": "maps/quicksilver_remake_1.24.sd7",
                    "extract": false
                },
                {
                    "url": "https://github.com/beyond-all-reason/Maps/releases/download/1.0/trefoil_remake_2.20.sd7",
                    "destination": "maps/trefoil_remake_2.20.sd7",
                    "extract": false
                }
            ],
            "nextgen": []
        },
        "launch": {
            "start_args": [
                "--menu",
                "rapid://byar-chobby:test"
            ],
            "engine": "105.1.1-582-gddec320 bar"
        },
        "title": "Beyond All Reason"
    },
    {
        "package": {
            "platform": "linux",
            "portable": false,
            "id": "dev-lobby-linux",
            "display": "Dev Lobby"
        },
        "display": {
            "title": "Spring Launcher"
        },
        "isolation": true,
        "auto_download": false,
        "auto_start": false,
        "no_downloads": true,
        "no_start_script": true,
        "load_dev_exts": false,
        "route_prd_to_nextgen": false,
        "github_log_repo": null,
        "downloads": {
            "games": [],
            "maps": [],
            "engines": [],
            "resources": [
                {
                    "url": "https://github.com/beyond-all-reason/spring/releases/download/spring_bar_%7BBAR105%7D105.1.1-582-gddec320/spring_bar_.BAR105.105.1.1-582-gddec320_linux-64-minimal-portable.7z",
                    "destination": "engine/105.1.1-582-gddec320 bar",
                    "extract": true
                }
            ],
            "nextgen": []
        },
        "launch": {
            "start_args": [
                "--menu",
                "BYAR Chobby $VERSION"
            ],
            "engine": "105.1.1-582-gddec320 bar"
        },
        "title": "Beyond All Reason"
    }
]
[2021-11-19 09:00:36.186] [info]  Default config:
{
    "package": {
        "platform": "linux",
        "portable": false,
        "id": "manual-linux",
        "display": "Alpha"
    },
    "display": {
        "title": "Spring Launcher"
    },
    "isolation": true,
    "auto_download": false,
    "auto_start": false,
    "no_downloads": false,
    "no_start_script": true,
    "load_dev_exts": false,
    "route_prd_to_nextgen": false,
    "github_log_repo": null,
    "downloads": {
        "games": [
            "byar:test",
            "chobby:test",
            "byar-chobby:test"
        ],
        "maps": [],
        "engines": [],
        "resources": [
            {
                "url": "https://github.com/beyond-all-reason/spring/releases/download/spring_bar_%7BBAR105%7D105.1.1-582-gddec320/spring_bar_.BAR105.105.1.1-582-gddec320_linux-64-minimal-portable.7z",
                "destination": "engine/105.1.1-582-gddec320 bar",
                "extract": true
            },
            {
                "url": "https://github.com/beyond-all-reason/Maps/releases/download/1.0/altored_divide_bar_remake_1.55.sd7",
                "destination": "maps/altored_divide_bar_remake_1.55.sd7",
                "extract": false
            },
            {
                "url": "https://github.com/beyond-all-reason/Maps/releases/download/1.0/boulder_beach_v1.sd7",
                "destination": "maps/boulder_beach_v1.sd7",
                "extract": false
            },
            {
                "url": "https://github.com/beyond-all-reason/Maps/releases/download/1.0/dsdr_4.0.sd7",
                "destination": "maps/dsdr_4.0.sd7",
                "extract": false
            },
            {
                "url": "https://github.com/beyond-all-reason/Maps/releases/download/1.0/quicksilver_remake_1.24.sd7",
                "destination": "maps/quicksilver_remake_1.24.sd7",
                "extract": false
            },
            {
                "url": "https://github.com/beyond-all-reason/Maps/releases/download/1.0/trefoil_remake_2.20.sd7",
                "destination": "maps/trefoil_remake_2.20.sd7",
                "extract": false
            }
        ],
        "nextgen": []
    },
    "launch": {
        "start_args": [
            "--menu",
            "rapid://byar-chobby:test"
        ],
        "engine": "105.1.1-582-gddec320 bar"
    },
    "title": "Beyond All Reason"
}
[2021-11-19 09:00:36.603] [info]  bridge: listening on port: 127.0.0.1:34089
[2021-11-19 09:00:36.604] [info]  Including extension: ./exts/bridge_download.js...
[2021-11-19 09:00:36.606] [info]  Including extension: ./exts/dev_extension_loader.js...
[2021-11-19 09:00:36.607] [info]  Including extension: ./exts/map_parser.js...
[2021-11-19 09:00:36.865] [info]  Including extension: ./exts/open_file.js...
[2021-11-19 09:00:36.869] [info]  Including extension: ./exts/replay_handler.js...
[2021-11-19 09:00:36.896] [info]  Including extension: ./exts/start_new_spring_handler.js...
[2021-11-19 09:00:36.897] [info]  Including extension: ./exts/track_files.js...
[2021-11-19 09:00:36.926] [info]  Including extension: ./exts/upload_log.js...
[2021-11-19 09:00:41.181] [info]  Step: {
    "name": "launcher_update"
}
[2021-11-19 09:00:41.182] [info]  Checking for launcher update
[2021-11-19 09:00:41.183] [info]  Checking for update
[2021-11-19 09:00:42.224] [info]  Update for version 1.1252.0 is not available (latest version: 1.1252.0, downgrade is disallowed).
[2021-11-19 09:00:42.224] [info]  No update available.
[2021-11-19 09:00:42.225] [info]  Step: {
    "name": "game",
    "item": "byar:test"
}
[2021-11-19 09:00:42.237] [info]  Download started: byar:test
[2021-11-19 09:00:42.281] [info]  pr-downloader 0.7-603-g31a5070 (linux64)

[2021-11-19 09:00:42.702] [info]  [Info] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/FileSystem/FileSystem.cpp:188:setWritePath():Using filesystem-writepath: /media/hdd/games/Beyond All Reason
[Info] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/pr-downloader.cpp:178:DownloadSetConfig():Free disk space: 104998 MB
[Info] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/CurlWrapper.cpp:62:DumpVersion():libcurl 7.73.0 OpenSSL/1.1.1i
[Info] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/CurlWrapper.cpp:42:GetTLSBackend():SSL backend #0: 'openssl' (ID: 1)
[Info] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/CurlWrapper.cpp:107:ValidateCaFile():Downloading https://springrts.com/dl/cacert.pem
[Progress] 100% [==============================] 299/299 
[2021-11-19 09:00:44.704] [info]  

[2021-11-19 09:00:44.705] [info]  [Progress]   0% [                              ] 0/0 
[2021-11-19 09:00:44.821] [warn]  [Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:468:processMessages():CURL error(1:77): Problem with the SSL CA cert (path? access rights?) 0 (https://repos.springrts.com/repos.gz)

[2021-11-19 09:00:46.823] [info]  

[2021-11-19 09:00:46.825] [warn]  [Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Rapid/RapidDownloader.cpp:189:ParseFD():Broken /media/hdd/games/Beyond All Reason/rapid/repos.springrts.com/repos.gz: 0

[2021-11-19 09:00:46.942] [warn]  [Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:81:DownloadUrl():Error in curl Problem with the SSL CA cert (path? access rights?) (error setting certificate verify locations:  CAfile: /etc/ssl/certs/ca-certificates.crt CApath: /etc/ssl/certs)
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:196:search():Error downloading https://springfiles.springrts.com/json.php?category=game&springname=byar:test 
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/main.cpp:196:main():No game found for byar:test
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/main.cpp:241:main():Error occurred while downloading: 1

[2021-11-19 09:00:46.944] [error] byar:test: [Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:81:DownloadUrl():Error in curl Problem with the SSL CA cert (path? access rights?) (error setting certificate verify locations:  CAfile: /etc/ssl/certs/ca-certificates.crt CApath: /etc/ssl/certs)
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:196:search():Error downloading https://springfiles.springrts.com/json.php?category=game&springname=byar:test 
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/main.cpp:196:main():No game found for byar:test
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/main.cpp:241:main():Error occurred while downloading: 1

[2021-11-19 09:03:09.568] [info]  User wants to upload?  Yes (Upload)
[2021-11-19 09:03:09.569] [info]  Uploading...
[2021-11-19 09:03:09.851] [error] Failed to upload log, copy and upload the log manually.
Reason: RequestError: certificate has expired.
[2021-11-19 09:03:09.851] [error] RequestError: certificate has expired
    at ClientRequest.<anonymous> (/tmp/.mount_BeyondZZsdFx/resources/app.asar/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/tmp/.mount_BeyondZZsdFx/resources/app.asar/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12)
`

**Comment by xyz32** [comment]
This workaround will fix it for fedora:
`sudo ln -s /etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt`

**Comment by epassaro** [comment]
Thanks! Doesn't work on openSUSE, but somehow you helped me to fix the issue.

In openSUSE just install the `ca-certificates-steamtricks` package.

**Comment by abma** [comment]
auto update of https://springrts.com/dl/cacert.pem was broken and so the download failed.

But thats file is just a fallback if the local trust-store can't be loaded from /etc/ssl/certs:

https://github.com/spring/pr-downloader/blob/master/src/Downloader/CurlWrapper.cpp#L17

**Comment by epassaro** [comment]
I'm closing this. Thanks to everyone.
