### ISSUE TITLE
can pr-downloader.exe download and extract win64 engines?

### ISSUE THREAD

**Issue by abma** [beyond-all-reason/BYAR-Chobby#60]
in a short test springlobby fails with "failed to extract engine":
https://github.com/springlobby/springlobby/issues/977#issuecomment-719913933

can you confirm that problem?

**Comment by Damgam** [comment]
Isn't this caused by the fact that SL is 32bit?

**Comment by abma** [comment]
no. current version of springlobby is 64bit only. also the issue was caused by an outdated 7zip lib:

https://github.com/springlobby/springlobby/issues/977#issuecomment-720148219
