### ISSUE TITLE
Spaces in AppImage BYAR filename

### ISSUE THREAD

**Issue by epassaro** [beyond-all-reason/BYAR-Chobby#61]
AppImage file is named `Beyond All Reason.AppImage` but spaces are not  currently supported by AppImageKit (for example, with `appimaged`) as pointed [here](https://github.com/AppImage/AppImageKit/issues/678).

**Comment by gajop** [comment]
Sorry, what's the problem? The AppImages work fine for me. Did you encounter any issue?

**Comment by epassaro** [comment]
> __AppImageKit__  is  a  concrete  implementation  of  the  AppImage  format  and  provides  tools such as `appimagetool` and `appimaged` for conveniently handling AppImages. 

> `appimaged` is an optional daemon that watches locations like `~/bin` and `~/Downloads` for AppImages and if it detects some, registers them with the system, so that they show up in the menu, have their icons show up, MIME types associated, etc. It also unregisters AppImages again from the system if they are deleted.

The BYAR AppImage runs fine if executed through the terminal or via double click. But fails when executed through the Applications Menu (after being registered by `appimaged`).

This is not strictly a bug.

**Comment by Mrlinkwii** [comment]
> The BYAR AppImage runs fine if executed through the terminal or via double click. But fails when executed through the Applications Menu (after being registered by `appimaged`).
> 
> This is not strictly a bug.

@epassaro it works here , opening though the applications Menu with  appimaged  , you may have to update appimaged ( it was updated recently ) 

im on 20.04 LTS

**Comment by epassaro** [comment]
:heavy_check_mark:  Works for me on Kubuntu 18.04 with version: `appimaged, continuous build (commit b096cd3), build 221 built on 2020-03-30 19:16:46 UTC`

:negative_squared_cross_mark:  Does not work on openSUSE Tumbleweed with version: `Version: 9~pre.1495805837.d05eac1`.


So probably they broke something upstream. I'm closing this.
