### ISSUE TITLE
[Linux] Wrong icon file path

### ISSUE THREAD

**Issue by epassaro** [beyond-all-reason/BYAR-Chobby#62]
I'm not sure if it's related to `appimaged` or BYAR, but icon is not displayed in Applications Menu because is located under `~/.local/share/icons/hicolor/0x0/apps/` and the `.desktop` file is looking for it at `~/.local/share/icons/`. Moving the icon to that location fixes the problem.

Also the `Name` field in the desktop entry is `Beyond-All-Reason` with dashes `-`.

**Comment by MooseOnTheLoose** [comment]
I think this is a limitation of appimage but I am open to being corrected. It's a long standing issue with more info here: https://github.com/AppImage/AppImageKit/issues/346

**Comment by p2004a** [comment]
obsolete/won't fix
