### ISSUE TITLE
Missing feature - updating player ingame time ranks

### ISSUE THREAD

**Issue by PtaQQ** [beyond-all-reason/BYAR-Chobby#64]
Currently not implemented in byar-chobby protocol, Spring-lobby uses the following scheme: 

Rank 1: 0 Hours
Rank 2: 5 Hours
Rank 3: 15 Hours
Rank 4: 30 Hours
Rank 5: 100 Hours
Rank 6: 300 Hours
Rank 7: 1000 Hours
Rank 8: 3000 Hours

**Comment by Beherith** [comment]
fixed
