### ISSUE TITLE
Duplicate install folder after launcher updating

### ISSUE THREAD

**Issue by JackCarterSmith** [beyond-all-reason/BYAR-Chobby#65]
When you launch update from the launcher, this download new installer and run it with default value.
In the case you've installed your game on a directory different from default installer value like "D:\BAR", the launcher make a new install on the default install path (in AppData).

It's can be possible to be retrieve install data from the previous install to update on the right install directory?

**Comment by MooseOnTheLoose** [comment]
Closing as a duplicate of #181
