### ISSUE TITLE
[Feature] Allow friends of host to join private battles without a password

### ISSUE THREAD

**Issue by jere0500** [beyond-all-reason/BYAR-Chobby#654]
# Idea
I often play private games with close friends.
While it is easy for them to join via password. I find this process somewhat tedious. 

Therefore, I would like to add a checkmark when requesting a private lobby.
 It should bypass the need to enter the password for friends. Something similar to what was discussed here: #426 

# Progress
I have already written some simple code for it.

![Screenshot_20240423_143310](https://github.com/beyond-all-reason/BYAR-Chobby/assets/123008073/1e338d5c-7359-43f1-b577-a4bf6e453ef3)

I am currently evaluating a way of implementing the necessary backend changes in the teiserver.

**Comment by AntlerForce** [comment]
Closed via #665
