### ISSUE TITLE
[FR] Make !ring sound different from ingame ping sound

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/BYAR-Chobby#703]
A lot of times when you're in a replay, and waiting for a match to finish, you can't hear that people are ringing you in lobby, because it's the same exact ring sound as in the replay you're watching.

**Comment by FIr3baL** [comment]
good idea.
I recently added ring to bypassed command when you are "in game". Now we have the ring, but it sounds same as the ring from replays itself.
For now: You can turn up the notification volume in lobby settings. This way you should able to seperate them.
I ask a sound dev for a new ring sound....

**Comment by FIr3baL** [comment]
You should also see a notification popup in the bottom right corner, when you get rang from lobby. See pic
![grafik](https://github.com/beyond-all-reason/BYAR-Chobby/assets/32598847/6b5c5d0b-c847-4b71-9743-dabf51efcd88)

**Comment by FIr3baL** [comment]
done with https://github.com/beyond-all-reason/BYAR-Chobby/pull/738
