### ISSUE TITLE
Show rating based on lobby team size rather than number of players

### ISSUE THREAD

**Issue by jauggy** [beyond-all-reason/BYAR-Chobby#707]
Currently when I join an empty lobby it shows my Duel rating. Then as players join it will then show my Team rating. I think it should just show the rating based on the team size of the lobby.

**Comment by StanczakDominik** [comment]
Except team size isn't sufficient, you also need Team Count because FFA exists :(

**Comment by jauggy** [comment]
Based on discussions with Fireball, this is a SPADS issue.
https://discord.com/channels/549281623154229250/549282587487502347/1257007874631274577
https://discord.com/channels/549281623154229250/1254602686062399599
