### ISSUE TITLE
[FR] Background cache task

### ISSUE THREAD

**Issue by d5xtgr** [beyond-all-reason/BYAR-Chobby#712]
When I launch BAR, I have to wait five or ten minutes for it to cache everything it needs.  However, if I let it cache completely and then exit and restart the game without playing a match, I can load in right away the next time.  It would be nice to have a command to cache that I can run in the background (i.e. without launching the whole game) at a low priority a couple times per day with cron, so that when I launch the game it's ready more promptly.  A command-line argument to the game executable seems like the natural way to do it.

**Comment by p2004a** [comment]
Based on how you phrased it, I will assume Linux. Just run in the installation directory

```
ionice -c 3 find pool -type f -exec sh -c 'cat {} > /dev/null' \;
```

That's basically what caching in lobby does.

**Comment by d5xtgr** [comment]
> Based on how you phrased it, I will assume Linux.

Correct.

> ```
> grep -r invalid-not-found-string
> ```
> 
> run from the `pool` directory

That worked!  I didn't even consider that it was a system-level cache the game was referring to.  I spent some time reading up on how that works on Linux, and it looks like vmtouch will be my go-to solution for this.  Thank you very much!
