### ISSUE TITLE
Unable to login on app but is able to login on website

### ISSUE THREAD

**Issue by Bitcoinrocket** [beyond-all-reason/BYAR-Chobby#732]
I can log into the website, so I know that my username and password are correct. When I try to log in, I am told I need to confirm with a verification code sent to my email, but the code is never sent. Only the first code, used for the initial setup is sent, and when I try to use that code, I am told that it is incorrect. From the increasing number of "a code has been sent to email" messages on the menu, I hypothesize that there is some bug in the sending of the emails.

**Comment by FIr3baL** [comment]
If possible, open a ticket in discord. You might get faster help there.
Maybe sth. went wrong with your specific account.
https://discord.com/channels/549281623154229250/1047080297042280518

**Comment by Bitcoinrocket** [comment]
Hi,
I did it after your last message and my problem is fixed.

Thank you very much.

Have a nice day.

Eric

**Comment by Fletfast** [comment]
Hi @Bitcoinrocket ,

I tried to login a lot of times and after logging, I still didn't receive the code to my email, I used a different email and still have the same issue.

1. I registered successfully from the launcher
2. I received a code in my email,
3. I entered this code in the input field and after that, I was redirected to the login form.
4. I log in to a new account, and again I need to write code, but in this case, I never receive new code to my email.

This issue still exists...

**Comment by p2004a** [comment]
@Fletfast You need to contact moderation via Discord to resolve the issue, we don't perform account level support via public GitHub issues like this one.

About the issue: it's known, and it's discussed internally, hopefully some fixes will land soon.
