### ISSUE TITLE
chat font too high

### ISSUE THREAD

**Issue by PtaQQ** [beyond-all-reason/BYAR-Chobby#9]
Text needs to be positioned lower/bigger text box.
<img width="803" alt="2019-10-13 19_37_12-Beyond all Reason" src="https://user-images.githubusercontent.com/29601271/66719741-fbde5a80-edf3-11e9-9e91-813d65e393da.png">

**Comment by Ruwetuin** [comment]
haven't noticed this since the high res font change has been reverted

**Comment by Ruwetuin** [comment]
i added back high res font and i dont see this anymore, while i tested in 1440p
